### ISSUE TITLE
Roadmap: Spring 2024

### ISSUE THREAD

**Issue by mrghosti3** [mrghosti3/nbteditor#7]
## Iterations

- [x] [Iteration 1](https://github.com/mrghosti3/nbteditor/milestone/1):
    - [x] #6 
    - [x] #8
- [x] [Iteration 2](https://github.com/mrghosti3/nbteditor/milestone/2):
    - [x] #9
    - [x] #10
    - [x] #12
- [x] [Iteration 3](https://github.com/mrghosti3/nbteditor/milestone/3):
    - [x] #13
    - [x] #17
- [x] [Iteration 4](https://github.com/mrghosti3/nbteditor/milestone/4):
    - [x] #14 
    - [x] #15

## Interesting features

> [!NOTE]
> These features are just mentions of what could implemented instead of some features mentioned above.

- #5 
- Small async runtime for watch server;
- Implement incremental reading from NBT file;

**Comment by mrghosti3** [comment]
The course module is over. Mostly accomplished all the set out goals. Closing the issue.
